### ISSUE TITLE
Cappi/Psuedo Cappi with DPDWR data of IMD

### ISSUE THREAD

**Issue by Space14Mann** [syedhamidali/PyScanCf#10]
[RSCHR_22MAR2022_121159_L2B_STD.zip](https://github.com/syedhamidali/PyScanCf/files/11477863/RSCHR_22MAR2022_121159_L2B_STD.zip)
Hye, i am a researcher working with DWR data, I am having a lot of Issues while visualizing and making cappi data with this kind of radar file using PyScanCf, data is as usual 250km range, 1600 gates, 360 azimuths, 10 elevation angles file, pyart functions of making radar grid does not work with this data. have tried many things. if little help is provided on this i would be very greatful.

**Comment by syedhamidali** [comment]
Can you email me at hamidsyed37@gmail.com?

**Comment by syedhamidali** [comment]
Check this notebook out
https://github.com/syedhamidali/test_scripts/blob/master/Nitig_Singh.ipynb

**Comment by Space14Mann** [comment]
Thanks, Dear Syed,
that was more than I could have asked for, it really helped me. looking forward to working and contributing in the near future.

**Comment by syedhamidali** [comment]
@Space14Mann, You can always me if it is not related to IMD radar stuff. And this doesn't belong to IMD, so it would be better to close this issue. Feel free to close it.

**Comment by Space14Mann** [comment]
sure my mistake, as i acquired from MOSDAC so it slipped in my mind as IMD, Thanks a lot.
