### ISSUE TITLE
 processed scan_type="C" data

### ISSUE THREAD

**Issue by Sanjitava** [syedhamidali/PyScanCf#12]
Sir, please share the example file where you processed scan_type="C" data, of GOA_C data,  (like CNI201124230735-IMD-C.nc, CNI201124230735-IMD-C.nc.1, this is from different station, I have this data of different time in a day, I am shearing only  one as example.

![Screenshot 2024-04-22 092939](https://github.com/syedhamidali/PyScanCf/assets/107239705/7a152d54-1766-4085-95d8-96bc82650c6c)

**Comment by Sanjitava** [comment]
Yes, sir

**Comment by Sanjitava** [comment]
please send your email.id,

**Comment by Sanjitava** [comment]
Sir, do you want this data ?

**Comment by syedhamidali** [comment]
Check your WhatsApp
