### ISSUE TITLE
Coordinate issue after rainfall calculation

### ISSUE THREAD

**Issue by Sanjitava** [syedhamidali/PyScanCf#13]
with plt.style.context(['dark_background']):R.plot(vmin = 0, vmax = 30, cmap = pyart.graph.cm.Carbone11)
![image](https://github.com/syedhamidali/PyScanCf/assets/107239705/4e273aca-b249-40b8-9a5b-b36154ecf538)

fig = plt.figure(figsize = [5,6])
ax = plt.axes(projection=ccrs.PlateCarree())
R_geo.plot(vmin = 0, vmax = 30, cmap = pyart.graph.cm.Carbone11, ax=ax)
add_map(ax=ax, b = 1, l=1)
![image](https://github.com/syedhamidali/PyScanCf/assets/107239705/f8621e2b-c801-48ab-b324-65c61b3b9f35)

**Comment by syedhamidali** [comment]
Did you checkout these examples?

https://github.com/syedhamidali/pyscancf_examples

especially recent ones?

**Comment by Sanjitava** [comment]
Yes Sir

**Comment by Sanjitava** [comment]
You can contract me in whatsapp 9163669402, email - biswassanjitava.2000@gmail.com for your suggestion
